### ISSUE TITLE
Inaccurate Book Title Captured to DB

### ISSUE THREAD

**Issue by ugonnaanyalemechi** [ugonnaanyalemechi/libraryManagementSystem#85]
While messing around with the book addition feature, I noticed that each time I add a book to the DB, the first letter of the title is cut off in the DB.
![Screenshot 2024-07-25 002324](https://github.com/user-attachments/assets/eebfad3d-26c0-42dd-b274-344b6941a0d6)

**Comment by Paulthelol** [comment]
It appears this bug has been resolved in the #84 branch, try testing the add book feature there.

**Comment by ugonnaanyalemechi** [comment]
Not a bug -- issue occurs when addBook function is called without going through the menu process. Because the there is nothing in the buffer, and the function begins with a cin.ignore(), the first character of the book title is ignored while the rest of the characters are stored and sent to the DB. Just need to be mindful of this.

**Comment by ugonnaanyalemechi** [comment]
Not a bug -- issue occurs when addBook function is called without going through the menu process. Because the there is nothing in the buffer, and the function begins with a cin.ignore(), the first character of the book title is ignored while the rest of the characters are stored and sent to the DB. Just need to be mindful of this.
